#!/bin/sh
#
# Copies configuration from /boot
#

CONF_DIR=/boot/config

start() {
    cp -a $CONF_DIR/hostname /etc/hostname  # also read directly earlier in inittab
    cp -a $CONF_DIR/wpa_supplicant.conf /etc/wpa_supplicant.conf
    cp -a $CONF_DIR/direwolf.conf /etc/direwolf.conf

    # generate ssh keys on first boot
    if [ ! -e $CONF_DIR/dropbear_ecdsa_host_key -o ! -e $CONF_DIR/dropbear_ed25519_host_key ]
    then
        mount -o remount,rw /boot
        dropbearkey -t ecdsa -f $CONF_DIR/dropbear_ecdsa_host_key
        dropbearkey -t ed25519 -f $CONF_DIR/dropbear_ed25519_host_key
        mount -o remount,ro /boot
        echo asdf >> /tmp/config.log
    fi

    echo $CONF_DIR/dropbear_*_host_key >> /tmp/config.log
    cp -a $CONF_DIR/dropbear_*_host_key /etc/dropbear/
}

case "$1" in
  start)
  	start
	;;
  stop|restart|reload)
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
