#!/bin/sh
#
# Sets up WireGuard VPN connection(s)
#

export WG_ENDPOINT_RESOLUTION_RETRIES=infinity

start() {
    for conf in /etc/wireguard/*.conf
    do
        iface="$(basename -s.conf $conf)"
        printf "Starting WireGuard interface $iface: "

        /usr/bin/wg-quick up "$iface"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    done
}

stop() {
    for conf in /etc/wireguard/*.conf
    do
        iface="$(basename -s.conf $conf)"
        printf "Stopping WireGuard interface $iface: "

        /usr/bin/wg-quick down "$iface"
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    done
}

reload() {
    for conf in /etc/wireguard/*.conf
    do
        iface="$(basename -s.conf $conf)"
        printf "Reloading WireGuard interface $iface: "

        /usr/bin/wg syncconf "$iface" <(exec /usr/bin/wg-quick strip "$iface")
        [ $? = 0 ] && echo "OK" || echo "FAIL"
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
        reload
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
