#!/bin/sh
#
# Starts Dire Wolf Sound Card-based AX.25 TNC
#

# Allow a few customizations from a config file
test -r /etc/default/direwolf && . /etc/default/direwolf

start() {
    DIREWOLF_ARGS="$DIREWOLF_ARGS -t 0 -c /etc/direwolf.conf -l /var/log/direwolf/"

    printf "Starting Dire Wolf: "
    screen -list direwolf/DireWolf ||
        su -s /bin/sh direwolf -c "screen -d -m -S DireWolf -- /usr/bin/direwolf $DIREWOLF_ARGS"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping Dire Wolf: "
    su -s /bin/sh direwolf -c "screen -S DireWolf -X quit"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
