#!/bin/sh
#
# Starts Dire Wolf Sound Card-based AX.25 TNC
#

DIREWOLF_ARGS="-X 1"  # enable FX.25 by default

# Allow a few customizations from a config file
test -r /etc/default/direwolf && . /etc/default/direwolf

start() {
    DIREWOLF_ARGS="$DIREWOLF_ARGS -t 0 -c /etc/direwolf.conf -l /var/log/direwolf/"

    if [ ! -e /dev/sda1 ]
    then
        mkdir -p /var/log/direwolf
        chown direwolf:direwolf /var/log/direwolf
    elif [ -n "$(awk '$2~/\/mnt/' /proc/mounts)" ]
    then
         mkdir -p /mnt/direwolf-logs /var/log/direwolf
         mount -o bind /mnt/direwolf-logs/ /var/log/direwolf
    fi

    printf "Starting Dire Wolf: "
    start-stop-daemon -S -q -m -b -p /var/run/direwolf.pid -c direwolf -x /bin/sh -- -c \
                      "exec /usr/bin/direwolf $DIREWOLF_ARGS 2>&1 \
                       > >( ts -i '+%.s' | ts '[%Y-%m-%d %H:%M:%S]' \
                            >> /var/log/direwolf/direwolf.log )"
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping Dire Wolf: "
    start-stop-daemon -K -q -p /var/run/direwolf.pid
    [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
